services:
  - type: web
    name: aivaro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GMAIL_APP_PASSWORD
        sync: false
